baseURL: https://guide.remote.one
title: RemoteOne Guide
theme: book

# Book configuration
disablePathToLower: true

params:
  # show or hide table of contents for page
  BookShowToC: true
  # Set bundle to render side menu
  # if not specified file structure and weights will be used
  BookMenuBundle: /menu
